"""Train/holdout scenario split.

Rule: tuned skills/MCP equipping is developed ONLY on scenarios assigned
"train"; a holdout scenario is used purely to SELECT among equippings already
built on train, never to tune them (preregistration §7.1 — "the tuned
skills/MCP equipping must be developed on a held-out scenario split, never
tuned on the benchmark scenarios themselves"; DECISIONS.md Amendment 10).

This module is both the split's definition — a deterministic function of the
current scenario-id set — and the loader ``generator/gen.py`` consults to
refuse emitting tuned-equipping material for a holdout scenario
(``gen.py::enforce_no_holdout_equipping`` hard-fails ``make gen``).

``--write`` is always a manual, logged action; nothing runs it implicitly, so
the split changes only when a human runs it and records why.

Algorithm, re-split procedure and the flip-handling rules:
See docs/generator.md#splitpy.
"""

from __future__ import annotations

import hashlib
import math
import sys
from pathlib import Path
from typing import Literal

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SPECS_DIR = REPO_ROOT / "specs"
TOY_SPECS_DIR = SPECS_DIR / "_toy"
SPLIT_PATH = SPECS_DIR / "split.yaml"

Group = Literal["train", "holdout"]

# Bump only on a genuine algorithm change: that re-permutes every id, unlike
# an ordinary scenario addition, which only shifts the 60/40 cutoff.
SPLIT_ALGORITHM_VERSION = 1
SEED = "cdktn-bench-split-v1"
TRAIN_FRACTION = 0.6


def discover_spec_ids() -> list[str]:
    """Every non-toy spec id on disk (specs/*.yaml, stem == id per SCHEMA.md §0).

    ``specs/_toy/`` is excluded, the same convention ``gen.py::generate()``
    uses for local-registry.json. ``specs/split.yaml`` is excluded too: it is
    this module's own output, and would otherwise be read as a scenario id.
    """
    return sorted(
        p.stem for p in SPECS_DIR.glob("*.yaml") if p.name != SPLIT_PATH.name
    )


def compute_split(
    spec_ids: list[str],
    seed: str = SEED,
    train_fraction: float = TRAIN_FRACTION,
) -> dict[str, dict[str, object]]:
    """Deterministic {spec_id: {"group", "score", "rank"}} (docs/generator.md#splitpy).

    Pure function of (spec_ids, seed, train_fraction): no filesystem access, so
    it is reproducible off this repo.
    """
    scored = []
    for spec_id in spec_ids:
        digest = hashlib.sha256(f"{seed}:{spec_id}".encode()).hexdigest()
        score_hex = digest[:16]
        scored.append((int(score_hex, 16), score_hex, spec_id))
    scored.sort(key=lambda t: (t[0], t[2]))  # tie-break on id for full determinism

    n = len(scored)
    n_train = math.floor(train_fraction * n + 0.5)  # round-half-up

    assignments: dict[str, dict[str, object]] = {}
    for rank, (_score_int, score_hex, spec_id) in enumerate(scored):
        assignments[spec_id] = {
            "group": "train" if rank < n_train else "holdout",
            "score": score_hex,
            "rank": rank,
        }
    return assignments


def render_split_yaml(assignments: dict[str, dict[str, object]], generated_at: str) -> str:
    n = len(assignments)
    n_train = sum(1 for a in assignments.values() if a["group"] == "train")
    n_holdout = n - n_train
    header = f"""\
# specs/split.yaml — train/holdout scenario split (prereg §7.1, DECISIONS.md
# Amendment 10). GENERATED by `generator/split.py` — do not hand-edit the
# `assignments` block; re-run `uv run python generator/split.py --write` and
# log the diff in DECISIONS.md instead (see
# docs/generator.md#splitpy, "re-split procedure", for the full steps).
#
# Rule this file exists to enforce: tuned skills/MCP equipping is developed
# ONLY on scenarios assigned "train" below; a holdout scenario is used
# purely to SELECT among equippings already built on train, never to tune
# them. generator/gen.py's `enforce_no_holdout_equipping()` hard-fails
# `make gen` if a holdout scenario's generated task directory ever contains
# skill/MCP/plugin config (the same equipping-file discovery
# gates/equipping.py's hash already uses) — this file is what that check
# reads.
#
# algorithm_version: SPLIT_ALGORITHM_VERSION in generator/split.py — bump
#   only on a genuine algorithm change (re-permutes every id); ordinary
#   scenario additions just shift the 60/40 cutoff over the existing
#   per-id ranking, see docs/generator.md#splitpy.
# seed: the fixed string every id's score is hashed against — changing it
#   is equivalent to bumping algorithm_version (also re-permutes everyone).
# train_fraction: the target train share; n_train = round(train_fraction *
#   len(assignments)), round-half-up.
algorithm_version: {SPLIT_ALGORITHM_VERSION}
seed: {SEED!r}
train_fraction: {TRAIN_FRACTION}
generated_at: {generated_at!r}
counts:
  total: {n}
  train: {n_train}
  holdout: {n_holdout}
assignments:
"""
    lines = [header]
    for spec_id in sorted(assignments):
        a = assignments[spec_id]
        lines.append(f"  {spec_id}:\n")
        lines.append(f"    group: {a['group']}\n")
        lines.append(f"    score: {a['score']!r}\n")
        lines.append(f"    rank: {a['rank']}\n")
    return "".join(lines)


def load_split(path: Path = SPLIT_PATH) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} does not exist — run `uv run python generator/split.py --write` "
            "to create it (see DECISIONS.md Amendment 10)."
        )
    data = yaml.safe_load(path.read_text())
    if not isinstance(data, dict) or "assignments" not in data:
        raise ValueError(f"{path}: malformed split file (no top-level 'assignments' key)")
    return data


def spec_group(spec_id: str, split_data: dict | None = None) -> Group | None:
    """The split group for spec_id, or None if split.yaml has no entry yet.

    Callers enforcing anything for holdout scenarios must treat None as
    "nothing to enforce yet", never as an implicit default: defaulting to
    holdout blocks gen.py on scenarios too new to be split, and defaulting to
    train lets tuned-equipping material past the guard unnoticed.
    """
    if split_data is None:
        split_data = load_split()
    entry = split_data.get("assignments", {}).get(spec_id)
    if entry is None:
        return None
    group = entry["group"]
    if group not in ("train", "holdout"):
        raise ValueError(f"specs/split.yaml: spec {spec_id!r} has invalid group {group!r}")
    return group  # type: ignore[return-value]


def main(argv: list[str]) -> int:
    import datetime

    write = "--write" in argv
    spec_ids = discover_spec_ids()
    assignments = compute_split(spec_ids)
    generated_at = datetime.datetime.now(tz=datetime.UTC).date().isoformat()
    rendered = render_split_yaml(assignments, generated_at)

    if write:
        SPLIT_PATH.write_text(rendered)
        print(f"wrote {SPLIT_PATH.relative_to(REPO_ROOT)} ({len(spec_ids)} scenarios)")
    else:
        print(rendered, end="")
        print(
            "\n(dry run — pass --write to overwrite specs/split.yaml; "
            "see docs/generator.md#splitpy, re-split procedure, first)",
            file=sys.stderr,
        )

    for spec_id in sorted(assignments):
        a = assignments[spec_id]
        print(f"  {spec_id:32s} {a['group']:8s} rank={a['rank']}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
